FROM eclipse-temurin:21-jre
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/quarkus-app/lib/ /work/lib/
COPY --chown=1001:root target/quarkus-app/*.jar /work/
COPY --chown=1001:root target/quarkus-app/app/ /work/app/
COPY --chown=1001:root target/quarkus-app/quarkus/ /work/quarkus/

USER 1001

CMD ["java", "-jar", "quarkus-run.jar"]
