apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-payments
  labels:
    team: team-a
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-payments
  template:
    metadata:
      labels:
        team: team-a
        app: payments
    spec:
      containers:
        - name: app
          image: nginx:1.25
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
